# Site settings
title: "KIRKPINARKOKOREÇ"
email: kirkpinarkokorec@gmail.com
description: "Kavaklı Kırkpınar Kokoreç Yemek Salonu : kebap çeşitlerimiz, kelle paça çorbamız ve diğer lezzetlerimizle hizmetinizdeyiz. telefon:05426896900"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: 
email: kirkpinarkokorec@gmail.com   
facebook_username: "groups/2256498571237680/"
twitter_username: 
# instagram_username: 
  # Feel free to add more lines here 
telephone: "05426896900"
copyright: "KIRKPINAR KOKOREÇ"

# API settings
google_api_key: "AIzaSyD1ArbSymIo1mibUHPp8NNcVXGAqu41Zhc"

# Build settings
markdown: kramdown
